site_name: Airavata Documentation
 <div>0.16</div>

docs_dir: .

pages:
- <h5>Home</h5>: 'index.md'
- <h5>System Installations</h5>:
  - Airavata: 'Airavata-Installation.md'
  - PGA: 'PGA-Installation.md'
  - WSO2 IS: 'Own-WSO2-IS-Configuration.md'
  - Airavata Property File: 'airavata-properties.md'
- <h5>Configuration</h5>:
  - Admin Tutorials: 'Admin-Tutorials.md'
  - PGA: 'Gateway-Configurations.md'
  - WSO2 IS: 'WSO2-IS-Configuration.md'
- <h5>Gateway Maintenance</h5>:
  - <h6>Code Upgrades</h6>:
      - Airavata: 'Airavata-Upgrades.md'
      - PGA: 'PGA-Upgrades.md'
  - <h6>Admin Dashboard</h6>: 'Admin-Maintenance.md'
- <h5>Documentation</h5>:
  - User Tutorials: 'User-Tutorials.md'
  - User Profiles: 'User-Profiles.md'
  - Software Applications: 'Application-CookBook.md'
  - Airavata API: 'AiravataApi.md'
- <h5>Technical Documentation</h5>:
  - <h6>Sharing Documentation</h6>:
      - Index: 'Sharing-Docs.md'
      - Sharing CPI: 'CPI.md'
      - Sharing Models: 'Models.md'
- <h5>FAQ</h5>: 'FAQ.md'
- <h5>Contact Us</h5>: 'Contact-Us.md'

theme: readthedocs

extra_css:
  - css/extra.css
