site_name: Apache Airavata Admin User Docs
site_url: https://airavata.apache.org/
site_description: Apache Airavata Documentation

repo_url: https://github.com/apache/airavata-docs

docs_dir: docs

nav:
- Home: 'index.md'
- Admin User Documentation:
  - Quick Start: 'user-documentation/quick-start.md'
  - Tutorial: 'user-documentation/tutorials.md'
  - Application Catalog: 'user-documentation/application-catalog.md'
  - Advance Application Inputs: 'user-documentation/advance-inputs.md'
  - Experiment Statistis: 'user-documentation/exp-statistics.md'
  - Manage Users: 'user-documentation/manage-users.md'
  - Admin User Groups: 'user-documentation/admin-groups.md'
  - Credential Store: 'user-documentation/cred-store.md'
  - Group Resource Profile: 'user-documentation/group-resource-profile.md'
  - Gateway Resource Profile: 'user-documentation/gtwy-resource-profile.md'
  - Manage Notices: 'user-documentation/manage-notices.md'
  - Extended User Profile: 'user-documentation/extended-user-profile.md'
  - Developer Console: 'user-documentation/develop-console.md'
  - Django Theme Construction: 'user-documentation/django-theme.md'
  - Django Releases: 'user-documentation/django-releases.md'
- Contact Us: 'contact-us.md'

theme: readthedocs

extra_css:
  - css/extra.css

extra_javascript:
  - js/clipboard.min.js
  - js/clipboard_init.js

markdown_extensions:
  - toc:
     permalink: 
  - admonition
