site_name: Airavata Documentation
docs_dir: .

pages:
- Home: 'index.md'
- Installations:
  - Airavata: 'Airavata-Installation.md'
  - PGA: 'PGA-Installation.md'
  - Airavata Property File: 'airavata-properties.md'
- Configuration:
  - PGA: 'Gateway-Configurations.md'
  - WSO2 IS: 'WSO2-IS-Configuration.md'
- Documentation:
  - User Profiles: User-Profiles.md
  - Applications: Application-CookBook.md
  - Airavata API: AiravataApi.md
- FAQ: FAQ.md
- Contact Us: Contact-Us.md

theme: readthedocs

extra_css:
  - css/extra.css